spring.application.name=casasrurales
spring.datasource.url=jdbc:mysql://localhost:3306/casas_rurales?createDatabaseIfNotExist=true&serverTimezone=America/Bogota
spring.datasource.username=root
#Poner su contrasena
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.upload.dir=uploads
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=20MB
